version: '3'
services:

    #PHP Service
    app-monitoring:
        build:
            args:
                user: nginx
                uid: 1000
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app-monitoring
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app-monitoring
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network

    #Nginx Service
    webserver-monitoring:
        image: nginx:alpine
        container_name: webserver-monitoring
        restart: unless-stopped
        tty: true
        ports:
            - "81:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db-monitoring:
        image: mysql:5.7.22
        container_name: db-monitoring
        restart: unless-stopped
        tty: true
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            ERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
